#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyXeMay")]
	public partial class QuanLyBanXeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_HoaDon(CT_HoaDon instance);
    partial void UpdateCT_HoaDon(CT_HoaDon instance);
    partial void DeleteCT_HoaDon(CT_HoaDon instance);
    partial void InsertDiaChi(DiaChi instance);
    partial void UpdateDiaChi(DiaChi instance);
    partial void DeleteDiaChi(DiaChi instance);
    partial void InsertHangXe(HangXe instance);
    partial void UpdateHangXe(HangXe instance);
    partial void DeleteHangXe(HangXe instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiXe(LoaiXe instance);
    partial void UpdateLoaiXe(LoaiXe instance);
    partial void DeleteLoaiXe(LoaiXe instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    #endregion
		
		public QuanLyBanXeDataContext() : 
				base(global::DAL.Properties.Settings.Default.QuanLyXeMayConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanXeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanXeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanXeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyBanXeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this.GetTable<CT_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<DiaChi> DiaChis
		{
			get
			{
				return this.GetTable<DiaChi>();
			}
		}
		
		public System.Data.Linq.Table<HangXe> HangXes
		{
			get
			{
				return this.GetTable<HangXe>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiXe> LoaiXes
		{
			get
			{
				return this.GetTable<LoaiXe>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HoaDon")]
	public partial class CT_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHopDong;
		
		private string _maHoaDon;
		
		private double _giaBan;
		
		private double _thue;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<HopDong> _HopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHopDongChanging(string value);
    partial void OnmaHopDongChanged();
    partial void OnmaHoaDonChanging(string value);
    partial void OnmaHoaDonChanged();
    partial void OngiaBanChanging(double value);
    partial void OngiaBanChanged();
    partial void OnthueChanging(double value);
    partial void OnthueChanged();
    #endregion
		
		public CT_HoaDon()
		{
			this._HoaDon = default(EntityRef<HoaDon>);
			this._HopDong = default(EntityRef<HopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHopDong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHopDong
		{
			get
			{
				return this._maHopDong;
			}
			set
			{
				if ((this._maHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHopDongChanging(value);
					this.SendPropertyChanging();
					this._maHopDong = value;
					this.SendPropertyChanged("maHopDong");
					this.OnmaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float NOT NULL")]
		public double giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thue", DbType="Float NOT NULL")]
		public double thue
		{
			get
			{
				return this._thue;
			}
			set
			{
				if ((this._thue != value))
				{
					this.OnthueChanging(value);
					this.SendPropertyChanging();
					this._thue = value;
					this.SendPropertyChanged("thue");
					this.OnthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_HoaDon", Storage="_HoaDon", ThisKey="maHoaDon", OtherKey="maHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._maHoaDon = value.maHoaDon;
					}
					else
					{
						this._maHoaDon = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_CT_HoaDon", Storage="_HopDong", ThisKey="maHopDong", OtherKey="maHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._maHopDong = value.maHopDong;
					}
					else
					{
						this._maHopDong = default(string);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaChi")]
	public partial class DiaChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDiaChi;
		
		private string _tinhThanh;
		
		private string _soNha;
		
		private string _phuongXa;
		
		private string _quanHuyen;
		
		private string _quocGia;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntitySet<NhaCungCap> _NhaCungCaps;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    partial void OntinhThanhChanging(string value);
    partial void OntinhThanhChanged();
    partial void OnsoNhaChanging(string value);
    partial void OnsoNhaChanged();
    partial void OnphuongXaChanging(string value);
    partial void OnphuongXaChanged();
    partial void OnquanHuyenChanging(string value);
    partial void OnquanHuyenChanged();
    partial void OnquocGiaChanging(string value);
    partial void OnquocGiaChanged();
    #endregion
		
		public DiaChi()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._NhaCungCaps = new EntitySet<NhaCungCap>(new Action<NhaCungCap>(this.attach_NhaCungCaps), new Action<NhaCungCap>(this.detach_NhaCungCaps));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhThanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tinhThanh
		{
			get
			{
				return this._tinhThanh;
			}
			set
			{
				if ((this._tinhThanh != value))
				{
					this.OntinhThanhChanging(value);
					this.SendPropertyChanging();
					this._tinhThanh = value;
					this.SendPropertyChanged("tinhThanh");
					this.OntinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNha", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string soNha
		{
			get
			{
				return this._soNha;
			}
			set
			{
				if ((this._soNha != value))
				{
					this.OnsoNhaChanging(value);
					this.SendPropertyChanging();
					this._soNha = value;
					this.SendPropertyChanged("soNha");
					this.OnsoNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuongXa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phuongXa
		{
			get
			{
				return this._phuongXa;
			}
			set
			{
				if ((this._phuongXa != value))
				{
					this.OnphuongXaChanging(value);
					this.SendPropertyChanging();
					this._phuongXa = value;
					this.SendPropertyChanged("phuongXa");
					this.OnphuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quanHuyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string quanHuyen
		{
			get
			{
				return this._quanHuyen;
			}
			set
			{
				if ((this._quanHuyen != value))
				{
					this.OnquanHuyenChanging(value);
					this.SendPropertyChanging();
					this._quanHuyen = value;
					this.SendPropertyChanged("quanHuyen");
					this.OnquanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string quocGia
		{
			get
			{
				return this._quocGia;
			}
			set
			{
				if ((this._quocGia != value))
				{
					this.OnquocGiaChanging(value);
					this.SendPropertyChanging();
					this._quocGia = value;
					this.SendPropertyChanged("quocGia");
					this.OnquocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_KhachHang", Storage="_KhachHangs", ThisKey="maDiaChi", OtherKey="maDiaChi")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_NhaCungCap", Storage="_NhaCungCaps", ThisKey="maDiaChi", OtherKey="maDiaChi")]
		public EntitySet<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this._NhaCungCaps;
			}
			set
			{
				this._NhaCungCaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_NhanVien", Storage="_NhanViens", ThisKey="maDiaChi", OtherKey="maDiaChi")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = null;
		}
		
		private void attach_NhaCungCaps(NhaCungCap entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = this;
		}
		
		private void detach_NhaCungCaps(NhaCungCap entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.DiaChi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangXe")]
	public partial class HangXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHang;
		
		private string _tenHang;
		
		private string _xuatXu;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHangChanging(string value);
    partial void OnmaHangChanged();
    partial void OntenHangChanging(string value);
    partial void OntenHangChanged();
    partial void OnxuatXuChanging(string value);
    partial void OnxuatXuChanged();
    #endregion
		
		public HangXe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHang
		{
			get
			{
				return this._maHang;
			}
			set
			{
				if ((this._maHang != value))
				{
					this.OnmaHangChanging(value);
					this.SendPropertyChanging();
					this._maHang = value;
					this.SendPropertyChanged("maHang");
					this.OnmaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenHang
		{
			get
			{
				return this._tenHang;
			}
			set
			{
				if ((this._tenHang != value))
				{
					this.OntenHangChanging(value);
					this.SendPropertyChanging();
					this._tenHang = value;
					this.SendPropertyChanged("tenHang");
					this.OntenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuatXu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string xuatXu
		{
			get
			{
				return this._xuatXu;
			}
			set
			{
				if ((this._xuatXu != value))
				{
					this.OnxuatXuChanging(value);
					this.SendPropertyChanging();
					this._xuatXu = value;
					this.SendPropertyChanged("xuatXu");
					this.OnxuatXuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangXe_Xe", Storage="_Xes", ThisKey="maHang", OtherKey="maHang")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.HangXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.HangXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHoaDon;
		
		private string _maNhanVien;
		
		private string _maKhachHang;
		
		private string _trangThai;
		
		private System.DateTime _ngayLap;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(string value);
    partial void OnmaHoaDonChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    #endregion
		
		public HoaDon()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="maHoaDon", OtherKey="maHoaDon")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="maKhachHang", OtherKey="maKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKhachHang = value.maKhachHang;
					}
					else
					{
						this._maKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHopDong;
		
		private string _maNhanVien;
		
		private string _maKhachHang;
		
		private string _maXe;
		
		private string _trangThai;
		
		private System.DateTime _ngayLap;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHopDongChanging(string value);
    partial void OnmaHopDongChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OnmaXeChanging(string value);
    partial void OnmaXeChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    #endregion
		
		public HopDong()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHopDong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHopDong
		{
			get
			{
				return this._maHopDong;
			}
			set
			{
				if ((this._maHopDong != value))
				{
					this.OnmaHopDongChanging(value);
					this.SendPropertyChanging();
					this._maHopDong = value;
					this.SendPropertyChanged("maHopDong");
					this.OnmaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maXe
		{
			get
			{
				return this._maXe;
			}
			set
			{
				if ((this._maXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaXeChanging(value);
					this.SendPropertyChanging();
					this._maXe = value;
					this.SendPropertyChanged("maXe");
					this.OnmaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="maHopDong", OtherKey="maHopDong")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDong", Storage="_KhachHang", ThisKey="maKhachHang", OtherKey="maKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._maKhachHang = value.maKhachHang;
					}
					else
					{
						this._maKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDong", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_HopDong", Storage="_Xe", ThisKey="maXe", OtherKey="maXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._maXe = value.maXe;
					}
					else
					{
						this._maXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhachHang;
		
		private string _tenKhachHang;
		
		private string _cmnd;
		
		private string _soDienThoaiKH;
		
		private string _emailKH;
		
		private System.DateTime _ngaySinh;
		
		private string _maDiaChi;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntityRef<DiaChi> _DiaChi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OntenKhachHangChanging(string value);
    partial void OntenKhachHangChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnsoDienThoaiKHChanging(string value);
    partial void OnsoDienThoaiKHChanged();
    partial void OnemailKHChanging(string value);
    partial void OnemailKHChanged();
    partial void OnngaySinhChanging(System.DateTime value);
    partial void OnngaySinhChanged();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._DiaChi = default(EntityRef<DiaChi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenKhachHang
		{
			get
			{
				return this._tenKhachHang;
			}
			set
			{
				if ((this._tenKhachHang != value))
				{
					this.OntenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._tenKhachHang = value;
					this.SendPropertyChanged("tenKhachHang");
					this.OntenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoaiKH", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string soDienThoaiKH
		{
			get
			{
				return this._soDienThoaiKH;
			}
			set
			{
				if ((this._soDienThoaiKH != value))
				{
					this.OnsoDienThoaiKHChanging(value);
					this.SendPropertyChanging();
					this._soDienThoaiKH = value;
					this.SendPropertyChanged("soDienThoaiKH");
					this.OnsoDienThoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string emailKH
		{
			get
			{
				return this._emailKH;
			}
			set
			{
				if ((this._emailKH != value))
				{
					this.OnemailKHChanging(value);
					this.SendPropertyChanging();
					this._emailKH = value;
					this.SendPropertyChanged("emailKH");
					this.OnemailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					if (this._DiaChi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="maKhachHang", OtherKey="maKhachHang")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDong", Storage="_HopDongs", ThisKey="maKhachHang", OtherKey="maKhachHang")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_KhachHang", Storage="_DiaChi", ThisKey="maDiaChi", OtherKey="maDiaChi", IsForeignKey=true)]
		public DiaChi DiaChi
		{
			get
			{
				return this._DiaChi.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._DiaChi.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._maDiaChi = value.maDiaChi;
					}
					else
					{
						this._maDiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiXe")]
	public partial class LoaiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoai;
		
		private string _tenLoai;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    #endregion
		
		public LoaiXe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiXe_Xe", Storage="_Xes", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNCC;
		
		private string _tenNCC;
		
		private string _soDienThoaiNCC;
		
		private string _emailNCC;
		
		private string _maDiaChi;
		
		private EntitySet<Xe> _Xes;
		
		private EntityRef<DiaChi> _DiaChi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNCCChanging(string value);
    partial void OnmaNCCChanged();
    partial void OntenNCCChanging(string value);
    partial void OntenNCCChanged();
    partial void OnsoDienThoaiNCCChanging(string value);
    partial void OnsoDienThoaiNCCChanged();
    partial void OnemailNCCChanging(string value);
    partial void OnemailNCCChanged();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			this._DiaChi = default(EntityRef<DiaChi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenNCC
		{
			get
			{
				return this._tenNCC;
			}
			set
			{
				if ((this._tenNCC != value))
				{
					this.OntenNCCChanging(value);
					this.SendPropertyChanging();
					this._tenNCC = value;
					this.SendPropertyChanged("tenNCC");
					this.OntenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoaiNCC", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string soDienThoaiNCC
		{
			get
			{
				return this._soDienThoaiNCC;
			}
			set
			{
				if ((this._soDienThoaiNCC != value))
				{
					this.OnsoDienThoaiNCCChanging(value);
					this.SendPropertyChanging();
					this._soDienThoaiNCC = value;
					this.SendPropertyChanged("soDienThoaiNCC");
					this.OnsoDienThoaiNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string emailNCC
		{
			get
			{
				return this._emailNCC;
			}
			set
			{
				if ((this._emailNCC != value))
				{
					this.OnemailNCCChanging(value);
					this.SendPropertyChanging();
					this._emailNCC = value;
					this.SendPropertyChanged("emailNCC");
					this.OnemailNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					if (this._DiaChi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Xe", Storage="_Xes", ThisKey="maNCC", OtherKey="maNCC")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_NhaCungCap", Storage="_DiaChi", ThisKey="maDiaChi", OtherKey="maDiaChi", IsForeignKey=true)]
		public DiaChi DiaChi
		{
			get
			{
				return this._DiaChi.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi.Entity = null;
						previousValue.NhaCungCaps.Remove(this);
					}
					this._DiaChi.Entity = value;
					if ((value != null))
					{
						value.NhaCungCaps.Add(this);
						this._maDiaChi = value.maDiaChi;
					}
					else
					{
						this._maDiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _cmnd;
		
		private System.DateTime _ngaySinh;
		
		private string _soDienThoaiNV;
		
		private string _email;
		
		private string _chucVu;
		
		private string _matKhau;
		
		private System.Data.Linq.Binary _hinhAnh;
		
		private string _maDiaChi;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntityRef<DiaChi> _DiaChi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnngaySinhChanging(System.DateTime value);
    partial void OnngaySinhChanged();
    partial void OnsoDienThoaiNVChanging(string value);
    partial void OnsoDienThoaiNVChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnchucVuChanging(string value);
    partial void OnchucVuChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnhinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnhinhAnhChanged();
    partial void OnmaDiaChiChanging(string value);
    partial void OnmaDiaChiChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._DiaChi = default(EntityRef<DiaChi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoaiNV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string soDienThoaiNV
		{
			get
			{
				return this._soDienThoaiNV;
			}
			set
			{
				if ((this._soDienThoaiNV != value))
				{
					this.OnsoDienThoaiNVChanging(value);
					this.SendPropertyChanging();
					this._soDienThoaiNV = value;
					this.SendPropertyChanged("soDienThoaiNV");
					this.OnsoDienThoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucVu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string chucVu
		{
			get
			{
				return this._chucVu;
			}
			set
			{
				if ((this._chucVu != value))
				{
					this.OnchucVuChanging(value);
					this.SendPropertyChanging();
					this._chucVu = value;
					this.SendPropertyChanged("chucVu");
					this.OnchucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhAnh", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary hinhAnh
		{
			get
			{
				return this._hinhAnh;
			}
			set
			{
				if ((this._hinhAnh != value))
				{
					this.OnhinhAnhChanging(value);
					this.SendPropertyChanging();
					this._hinhAnh = value;
					this.SendPropertyChanged("hinhAnh");
					this.OnhinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maDiaChi
		{
			get
			{
				return this._maDiaChi;
			}
			set
			{
				if ((this._maDiaChi != value))
				{
					if (this._DiaChi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDiaChiChanging(value);
					this.SendPropertyChanging();
					this._maDiaChi = value;
					this.SendPropertyChanged("maDiaChi");
					this.OnmaDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HopDong", Storage="_HopDongs", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaChi_NhanVien", Storage="_DiaChi", ThisKey="maDiaChi", OtherKey="maDiaChi", IsForeignKey=true)]
		public DiaChi DiaChi
		{
			get
			{
				return this._DiaChi.Entity;
			}
			set
			{
				DiaChi previousValue = this._DiaChi.Entity;
				if (((previousValue != value) 
							|| (this._DiaChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaChi.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._DiaChi.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maDiaChi = value.maDiaChi;
					}
					else
					{
						this._maDiaChi = default(string);
					}
					this.SendPropertyChanged("DiaChi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maXe;
		
		private string _tenXe;
		
		private string _maHang;
		
		private string _maLoai;
		
		private double _congSuat;
		
		private int _doCaoYen;
		
		private double _dungTichBinhXang;
		
		private double _khoiLuong;
		
		private double _duongKinhPitTong;
		
		private string _mauSac;
		
		private string _phanKhoi;
		
		private int _soLuong;
		
		private double _giaThanh;
		
		private string _loaiPhanh;
		
		private string _loaiBanh;
		
		private string _maNCC;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntityRef<HangXe> _HangXe;
		
		private EntityRef<LoaiXe> _LoaiXe;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaXeChanging(string value);
    partial void OnmaXeChanged();
    partial void OntenXeChanging(string value);
    partial void OntenXeChanged();
    partial void OnmaHangChanging(string value);
    partial void OnmaHangChanged();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OncongSuatChanging(double value);
    partial void OncongSuatChanged();
    partial void OndoCaoYenChanging(int value);
    partial void OndoCaoYenChanged();
    partial void OndungTichBinhXangChanging(double value);
    partial void OndungTichBinhXangChanged();
    partial void OnkhoiLuongChanging(double value);
    partial void OnkhoiLuongChanged();
    partial void OnduongKinhPitTongChanging(double value);
    partial void OnduongKinhPitTongChanged();
    partial void OnmauSacChanging(string value);
    partial void OnmauSacChanged();
    partial void OnphanKhoiChanging(string value);
    partial void OnphanKhoiChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OngiaThanhChanging(double value);
    partial void OngiaThanhChanged();
    partial void OnloaiPhanhChanging(string value);
    partial void OnloaiPhanhChanged();
    partial void OnloaiBanhChanging(string value);
    partial void OnloaiBanhChanged();
    partial void OnmaNCCChanging(string value);
    partial void OnmaNCCChanged();
    #endregion
		
		public Xe()
		{
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._HangXe = default(EntityRef<HangXe>);
			this._LoaiXe = default(EntityRef<LoaiXe>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maXe
		{
			get
			{
				return this._maXe;
			}
			set
			{
				if ((this._maXe != value))
				{
					this.OnmaXeChanging(value);
					this.SendPropertyChanging();
					this._maXe = value;
					this.SendPropertyChanged("maXe");
					this.OnmaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenXe
		{
			get
			{
				return this._tenXe;
			}
			set
			{
				if ((this._tenXe != value))
				{
					this.OntenXeChanging(value);
					this.SendPropertyChanging();
					this._tenXe = value;
					this.SendPropertyChanged("tenXe");
					this.OntenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maHang
		{
			get
			{
				return this._maHang;
			}
			set
			{
				if ((this._maHang != value))
				{
					if (this._HangXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHangChanging(value);
					this.SendPropertyChanging();
					this._maHang = value;
					this.SendPropertyChanged("maHang");
					this.OnmaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._LoaiXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congSuat", DbType="Float NOT NULL")]
		public double congSuat
		{
			get
			{
				return this._congSuat;
			}
			set
			{
				if ((this._congSuat != value))
				{
					this.OncongSuatChanging(value);
					this.SendPropertyChanging();
					this._congSuat = value;
					this.SendPropertyChanged("congSuat");
					this.OncongSuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doCaoYen", DbType="Int NOT NULL")]
		public int doCaoYen
		{
			get
			{
				return this._doCaoYen;
			}
			set
			{
				if ((this._doCaoYen != value))
				{
					this.OndoCaoYenChanging(value);
					this.SendPropertyChanging();
					this._doCaoYen = value;
					this.SendPropertyChanged("doCaoYen");
					this.OndoCaoYenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dungTichBinhXang", DbType="Float NOT NULL")]
		public double dungTichBinhXang
		{
			get
			{
				return this._dungTichBinhXang;
			}
			set
			{
				if ((this._dungTichBinhXang != value))
				{
					this.OndungTichBinhXangChanging(value);
					this.SendPropertyChanging();
					this._dungTichBinhXang = value;
					this.SendPropertyChanged("dungTichBinhXang");
					this.OndungTichBinhXangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiLuong", DbType="Float NOT NULL")]
		public double khoiLuong
		{
			get
			{
				return this._khoiLuong;
			}
			set
			{
				if ((this._khoiLuong != value))
				{
					this.OnkhoiLuongChanging(value);
					this.SendPropertyChanging();
					this._khoiLuong = value;
					this.SendPropertyChanged("khoiLuong");
					this.OnkhoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duongKinhPitTong", DbType="Float NOT NULL")]
		public double duongKinhPitTong
		{
			get
			{
				return this._duongKinhPitTong;
			}
			set
			{
				if ((this._duongKinhPitTong != value))
				{
					this.OnduongKinhPitTongChanging(value);
					this.SendPropertyChanging();
					this._duongKinhPitTong = value;
					this.SendPropertyChanged("duongKinhPitTong");
					this.OnduongKinhPitTongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mauSac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mauSac
		{
			get
			{
				return this._mauSac;
			}
			set
			{
				if ((this._mauSac != value))
				{
					this.OnmauSacChanging(value);
					this.SendPropertyChanging();
					this._mauSac = value;
					this.SendPropertyChanged("mauSac");
					this.OnmauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phanKhoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phanKhoi
		{
			get
			{
				return this._phanKhoi;
			}
			set
			{
				if ((this._phanKhoi != value))
				{
					this.OnphanKhoiChanging(value);
					this.SendPropertyChanging();
					this._phanKhoi = value;
					this.SendPropertyChanged("phanKhoi");
					this.OnphanKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaThanh", DbType="Float NOT NULL")]
		public double giaThanh
		{
			get
			{
				return this._giaThanh;
			}
			set
			{
				if ((this._giaThanh != value))
				{
					this.OngiaThanhChanging(value);
					this.SendPropertyChanging();
					this._giaThanh = value;
					this.SendPropertyChanged("giaThanh");
					this.OngiaThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiPhanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string loaiPhanh
		{
			get
			{
				return this._loaiPhanh;
			}
			set
			{
				if ((this._loaiPhanh != value))
				{
					this.OnloaiPhanhChanging(value);
					this.SendPropertyChanging();
					this._loaiPhanh = value;
					this.SendPropertyChanged("loaiPhanh");
					this.OnloaiPhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiBanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string loaiBanh
		{
			get
			{
				return this._loaiBanh;
			}
			set
			{
				if ((this._loaiBanh != value))
				{
					this.OnloaiBanhChanging(value);
					this.SendPropertyChanging();
					this._loaiBanh = value;
					this.SendPropertyChanged("loaiBanh");
					this.OnloaiBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_HopDong", Storage="_HopDongs", ThisKey="maXe", OtherKey="maXe")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangXe_Xe", Storage="_HangXe", ThisKey="maHang", OtherKey="maHang", IsForeignKey=true)]
		public HangXe HangXe
		{
			get
			{
				return this._HangXe.Entity;
			}
			set
			{
				HangXe previousValue = this._HangXe.Entity;
				if (((previousValue != value) 
							|| (this._HangXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._HangXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._maHang = value.maHang;
					}
					else
					{
						this._maHang = default(string);
					}
					this.SendPropertyChanged("HangXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiXe_Xe", Storage="_LoaiXe", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public LoaiXe LoaiXe
		{
			get
			{
				return this._LoaiXe.Entity;
			}
			set
			{
				LoaiXe previousValue = this._LoaiXe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._LoaiXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(string);
					}
					this.SendPropertyChanged("LoaiXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Xe", Storage="_NhaCungCap", ThisKey="maNCC", OtherKey="maNCC", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._maNCC = value.maNCC;
					}
					else
					{
						this._maNCC = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
}
#pragma warning restore 1591
